Hugging Face Decoder
### 인터넷이 연결되어야 한다.

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.2 MB 23.4 MB/s 
     |████████████████████████████████| 6.6 MB 54.7 MB/s 
     |████████████████████████████████| 86 kB 5.4 MB/s 
     |████████████████████████████████| 596 kB 59.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


```
from transformers import TFAutoModel, AutoTokenizer
model = TFAutoModel.from_pretrained("<model_name>")
tokenizer = AutoTokenizer.from_pretrained("<model_name>")
```

## Tokenizer 실습

In [12]:
from transformers import AutoModel, AutoTokenizer, BertTokenizer

In [13]:
model_name  = 'bert-base-multilingual-cased'
model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name) # 모델에 해당하는 tokenizer가 자동적으로 불러와

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [14]:
print(tokenizer.vocab_size)

119547


In [15]:
for i, key in enumerate(tokenizer.get_vocab()):
    print(key)
    if i > 20:
        break

##トの
Museum
ක
सर्वात
болалуш
باليمن
рассказывает
##zler
003
##рения
##krajina
báo
description
язку
##ंदर
egyszerű
##徇
##۶
火
##gazione
##άν
##洸


In [16]:
text = "이순신은 조선 중기의 무신이다."
print(type(tokenizer))

<class 'transformers.models.bert.tokenization_bert_fast.BertTokenizerFast'>


In [17]:
tokenized_input_text = tokenizer(text, return_tensors="pt")

for key, value in tokenized_input_text.items():
    print("{} :\n\t{}".format(key, value))

# input_ids : 단어장
# 	tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
#           25387,  11925,    119,    102]])
# token_type_ids : [SEP] 토큰을 기준으로 문장을 2개로 나눌 때,
# 첫번째 문자일 때는 0으로 지정하고, 
# 2번째 문장일 때는 1로 지정한다.
# 	tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# attention_mask : padding이 아닌 토큰은 1, padding 토큰이면 0 
# 	tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

input_ids :
	tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
token_type_ids :
	tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
attention_mask :
	tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [18]:
# 같은 표현식
print(tokenized_input_text['input_ids'])# input text를 tokenizing한 후 vocab id
print(tokenized_input_text.input_ids)

tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])


In [19]:
print(tokenized_input_text['token_type_ids'])# segment id (sentA or sentB)
print(tokenized_input_text.token_type_ids)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [20]:
print(tokenized_input_text['attention_mask'])# special token(pad, cls, sep) or not
print(tokenized_input_text.attention_mask )

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [21]:
# '##'은 토큰끼리 이어진다는 것을 의미한다.
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.']


In [22]:
# ['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.']
# 이 토큰을 숫자로 표현 : [9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119]
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)

[9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119]


In [24]:
# 숫자를 문장으로 복귀
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선 중기의 무신이다.


In [25]:
# add_special_tokens=True로 변경한 후 encoding, decoding해볼 것
input_ids = tokenizer.encode(text, add_special_tokens=True)
print(input_ids)

[101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102]


In [26]:
# 숫자를 문장으로 복귀, 앞의 add_special_tokens=True 때문에 [CLS], [SEP]를 넣어준다.
# ex) [CLS] 이순신은 조선 중기의 무신이다. [SEP]
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

[CLS] 이순신은 조선 중기의 무신이다. [SEP]


option

In [28]:
# max_len이 5라서 토큰은 5개로 제한된다.
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 5,
    truncation = True
)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선']


In [29]:
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 5,
    truncation = True
)
print(input_ids)

[9638, 119064, 25387, 10892, 59906]


In [31]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선


In [32]:
print(tokenizer.pad_token)

[PAD]


In [34]:
print(tokenizer.pad_token_id)

0


In [37]:
# max_length를 변경해보고 출력 결과를 본다.
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 20,
    padding = "max_length"
)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']


In [38]:
# max_length를 변경해보고 출력 결과를 본다.
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 20,
    padding = "max_length"
)
print(input_ids)

[9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [39]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선 중기의 무신이다. [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]


새로운 토큰을 추가해보자!

In [44]:
text = "깟빼뜨랑 리뿔이 뜨럽거 므리커럭이 케쇼쇼쇽 나오애쇼쇼쇼 우뤼갸갸갸 청쇼랴료다혀뚜요"

# tokenized_text
tokenized_text = tokenizer.tokenize(text, add_special_tokens = False)
print(tokenized_text)

# input ids
input_ids = tokenizer.encode(text,add_special_tokens = False)
print(input_ids)

# decoded ids
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

# '[UNK] 토큰이 생성되었기 때문에, '[UNK]에 해당되는 단어를 따로 등록할 필요가 있다.
# 결과 : 

['[UNK]', '리', '##뿔', '##이', '뜨', '##럽', '##거', '므', '##리', '##커', '##럭', '##이', '[UNK]', '나', '##오', '##애', '##쇼', '##쇼', '##쇼', '[UNK]', '청', '##쇼', '##랴', '##료', '##다', '##혀', '##뚜', '##요']
[100, 9238, 119021, 10739, 9151, 118867, 41521, 9308, 12692, 106826, 118864, 10739, 100, 8982, 28188, 119121, 119060, 119060, 119060, 100, 9751, 119060, 118862, 38688, 11903, 80579, 118841, 48549]
[UNK] 리뿔이 뜨럽거 므리커럭이 [UNK] 나오애쇼쇼쇼 [UNK] 청쇼랴료다혀뚜요


In [45]:
# [UNK] 토큰에 해당되는 단어장에 등록해준다.
added_token_num = tokenizer.add_tokens(["깟빼뜨랑", "케쇼쇼쇽", "우뤼갸갸갸"])
print(added_token_num)

3


In [47]:
# 토큰을 추가했기 때문에 다시 토큰화하면 UNK 토큰이 사라졌다.
tokenized_text = tokenizer.tokenize(text, add_special_tokens = False)
print(tokenized_text)

# input ids
input_ids = tokenizer.encode(text,add_special_tokens = False)
print(input_ids)

# decoded ids
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['깟빼뜨랑', '리', '##뿔', '##이', '뜨', '##럽', '##거', '므', '##리', '##커', '##럭', '##이', '케쇼쇼쇽', '나', '##오', '##애', '##쇼', '##쇼', '##쇼', '우뤼갸갸갸', '청', '##쇼', '##랴', '##료', '##다', '##혀', '##뚜', '##요']
[119547, 9238, 119021, 10739, 9151, 118867, 41521, 9308, 12692, 106826, 118864, 10739, 119548, 8982, 28188, 119121, 119060, 119060, 119060, 119549, 9751, 119060, 118862, 38688, 11903, 80579, 118841, 48549]
깟빼뜨랑 리뿔이 뜨럽거 므리커럭이 케쇼쇼쇽 나오애쇼쇼쇼 우뤼갸갸갸 청쇼랴료다혀뚜요


In [48]:
# 토큰을 새로 생성해보자. 
# 지금은 hyerim이 한 토큰인데, 토큰이 없기 때문에 hy, eri 등으로 나눠진다.
text = "[hyerim]이순신은 조선 중기의 무신이다.[/hyerim]"

tokenized_text = tokenizer.tokenize(text, add_special_tokens = False)
print(tokenized_text)

# input ids
input_ids = tokenizer.encode(text,add_special_tokens = False)
print(input_ids)

# decoded ids
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['[', 'hy', '##eri', '##m', ']', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[', '/', 'hy', '##eri', '##m', ']']
[164, 15165, 13227, 10147, 166, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 164, 120, 15165, 13227, 10147, 166]
[ hyerim ] 이순신은 조선 중기의 무신이다. [ / hyerim ]


In [49]:
# 그러나 add_special_tokens으로 등록해놓으면 토큰이 지정된 상태로 분리된다.
text = "[hyerim]이순신은 조선 중기의 무신이다.[/hyerim]"

added_token_num += tokenizer.add_special_tokens({"additional_special_tokens" : ["[hyerim]", "[/hyerim]"]})

# 1. tokenized_text
tokenized_text = tokenizer.tokenize(text, add_special_tokens=False)
print(tokenized_text)

# 2. input ids
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)

# 3. decoded_ids
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['[hyerim]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[/hyerim]']
[119550, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 119551]
[hyerim] 이순신은 조선 중기의 무신이다. [/hyerim]


In [50]:
# single input
single_seg_input = tokenizer("이순신은 조선 중기의 무신이다.")

# Multiple input
multi_seg_input = tokenizer('이순신은 조선 중기의 무신이다.', "그는 임진왜란을 승리로 이끌었다.")

In [51]:
print("Single segment token(str) : {}".format(tokenizer.convert_ids_to_tokens(single_seg_input['input_ids'])))
print("Single segment token(int) : {}".format(single_seg_input['input_ids']))
print("Single segment type : {}".format(single_seg_input['token_type_ids']))

# Segments type이 서로 차이가 난다. single_seg_input 옵션과 multi_seg_input의 차이
print()
print("Single segment token(str) : {}".format(tokenizer.convert_ids_to_tokens(multi_seg_input['input_ids'])))
print("Single segment token(int) : {}".format(multi_seg_input['input_ids']))
print("Single segment type : {}".format(multi_seg_input['token_type_ids']))

Single segment token(str) : ['[CLS]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[SEP]']
Single segment token(int) : [101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102]
Single segment type : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Single segment token(str) : ['[CLS]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[SEP]', '그는', '임', '##진', '##왜', '##란', '##을', '승', '##리로', '이', '##끌', '##었다', '.', '[SEP]']
Single segment token(int) : [101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102, 17889, 9644, 18623, 119164, 49919, 10622, 9484, 100434, 9638, 118705, 17706, 119, 102]
Single segment type : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


Bert 모델 테스트

In [52]:
text = "이순신은 [MASK] 중기의 무신이다."
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

['이', '##순', '##신', '##은', '[MASK]', '중', '##기의', '무', '##신', '##이다', '.']


In [57]:
# [MASK]를 사용하여, 학습할 수 있다.
from transformers import pipeline

nlp_fill = pipeline('fill-mask', model = model_name)
nlp_fill("이순신은 [MASK] 중기의 무신이다.")

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.8747122883796692,
  'sequence': '이순신은 조선 중기의 무신이다.',
  'token': 59906,
  'token_str': '조선'},
 {'score': 0.0643644779920578,
  'sequence': '이순신은 청 중기의 무신이다.',
  'token': 9751,
  'token_str': '청'},
 {'score': 0.010954882018268108,
  'sequence': '이순신은 전 중기의 무신이다.',
  'token': 9665,
  'token_str': '전'},
 {'score': 0.004647170193493366,
  'sequence': '이순신은종 중기의 무신이다.',
  'token': 22200,
  'token_str': '##종'},
 {'score': 0.0036106768529862165,
  'sequence': '이순신은기 중기의 무신이다.',
  'token': 12310,
  'token_str': '##기'}]

In [58]:
# 그렇지만 nlp_fill은 마지막에 넣은 텍스트만 되는 것 같다.
nlp_fill("이순신은 조선 중기의 [MASK]이다.")
nlp_fill("이순신은 조선 [MASK]의 무신이다.")

[{'score': 0.1837785542011261,
  'sequence': '이순신은 조선 초기 의 무신이다.',
  'token': 106280,
  'token_str': '초기'},
 {'score': 0.1492975354194641,
  'sequence': '이순신은 조선시대 의 무신이다.',
  'token': 110670,
  'token_str': '##시대'},
 {'score': 0.13910074532032013,
  'sequence': '이순신은 조선조 의 무신이다.',
  'token': 20626,
  'token_str': '##조'},
 {'score': 0.0636642575263977,
  'sequence': '이순신은 조선 전 의 무신이다.',
  'token': 9665,
  'token_str': '전'},
 {'score': 0.044817160815000534,
  'sequence': '이순신은 조선자 의 무신이다.',
  'token': 13764,
  'token_str': '##자'}]

In [63]:
tokens_pt = tokenizer("이순신은 조선 중기의 무신이다.", return_tensors='pt')

for key, value in tokens_pt.items():
    print("{} : \w\t{}".format(key, value))

outputs = model(**tokens_pt)
last_hidden_state = outputs.last_hidden_state
pooler_output = outputs.pooler_output

print("\nToken wise output : {}, Pooled output : {}".format(last_hidden_state.shape,
                                                            pooler_output.shape))

input_ids : \w	tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
token_type_ids : \w	tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
attention_mask : \w	tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Token wise output : torch.Size([1, 13, 768]), Pooled output : torch.Size([1, 768])


In [61]:
print(pooler_output) # 모델의 출력결과도 획득 가능!

tensor([[ 3.4890e-01, -1.8015e-01, -5.9614e-02, -2.8366e-01, -2.8124e-02,
         -9.0362e-02,  4.2045e-02,  2.2453e-01, -2.8116e-01,  1.7483e-01,
         -2.1607e-02,  1.4198e-01, -3.1648e-01, -1.6163e-01,  2.3599e-01,
          2.0061e-01,  2.8029e-01, -1.2361e-01, -3.0099e-01, -3.8691e-02,
         -9.9856e-01, -3.3202e-01,  5.6800e-02, -2.6712e-01, -1.2116e-01,
          1.4856e-01,  1.2773e-01,  3.4447e-01,  2.2134e-01, -5.1869e-02,
         -1.2524e-01, -9.9894e-01,  6.4930e-01,  3.8137e-01,  3.1060e-01,
         -3.2780e-01,  9.8435e-02,  2.9994e-01,  2.4136e-01, -3.4889e-01,
         -7.3615e-02, -5.9105e-02,  6.2025e-02, -2.6999e-01, -2.3018e-01,
         -3.2142e-01, -8.9200e-02,  3.8871e-01, -4.1491e-01, -4.9184e-03,
          2.1343e-01,  2.0156e-01,  4.0043e-01, -1.2926e-01,  1.4154e-01,
          3.5468e-01, -4.0913e-02, -2.7519e-01,  5.2832e-02, -3.4929e-01,
         -1.4963e-01,  1.5575e-01,  6.3741e-02, -1.3282e-01,  2.7436e-02,
         -2.5254e-01,  1.2185e-01, -1.

In [65]:
# vocab을 새롭게 추가했다면, 반드시 model의 embedding layer 사이즈를 늘려주세요!
print(model.get_input_embeddings()) # Embedding(119547, 768, padding_idx=0)
model.resize_token_embeddings(tokenizer.vocab_size + added_token_num)
print(model.get_input_embeddings()) # Embedding(119552, 768)

Embedding(119547, 768, padding_idx=0)
Embedding(119552, 768)


In [67]:
# [ClS] 토큰을 활용해 문장의 유사도를 측정할 수 있다.
sent1 = tokenizer("오늘 하루 어떻게 보냈나요?", return_tensors="pt")
sent2 = tokenizer("오늘은 어떤 하루를 보내셨나요?", return_tensors="pt")
sent3 = tokenizer("이순신은 조선 중기의 무신이다.", return_tensors="pt")
sent4 = tokenizer("깟뻬뜨랑 리뿔이 뜨럽거 므리커럭이 케쇽 냐왜쇼 우뤼갸 쳥쇼섀료다혀뚜여", return_tensors="pt")

In [68]:
outputs = model(**sent1)
sent_1_pooler_output = outputs.pooler_output

outputs = model(**sent2)
sent_2_pooler_output = outputs.pooler_output

outputs = model(**sent3)
sent_3_pooler_output = outputs.pooler_output

outputs = model(**sent4)
sent_4_pooler_output = outputs.pooler_output

In [70]:
from torch import nn # neural network를 줄여서 nn이라고 이름을 줄였다.

cos = nn.CosineSimilarity(dim=1, eps=1e-6)
print(cos(sent_1_pooler_output, sent_2_pooler_output))

tensor([0.9757], grad_fn=<DivBackward0>)


In [71]:
print(cos(sent_2_pooler_output, sent_3_pooler_output))

tensor([0.6075], grad_fn=<DivBackward0>)


In [72]:
print(cos(sent_3_pooler_output, sent_4_pooler_output))

tensor([0.5997], grad_fn=<DivBackward0>)


In [74]:
# 1번 문장과 4번 문장은 유사도가 매우 높은데 이유를 모르겠다.
# 사람이 보기에는 매우 다른 문장 같은데....
print(cos(sent_1_pooler_output, sent_4_pooler_output))

tensor([0.9258], grad_fn=<DivBackward0>)
