### 참조 : https://codetorial.net/tensorflow/basics_of_tensor.html

#### 텐서 (Tensor)는 다차원 배열 (Multi-dimensional Array)입니다.
#### 텐서 (Tensor)는 벡터 (Vector)와 행렬 (Matrix)을 일반화한 것이며, 3차원 이상으로 확장 가능
#### 텐서 (Tensor)는 TensorFlow의 가장 주요한 객체이며, TensorFlow의 작업은 주로 텐서의 연산으로 이루어집니다.
#### 즉, TensorFlow는 텐서 (Tensor)를 정의하고 연산을 수행하도록 하는 프레임워크 (Framework)입니다.

In [5]:
import tensorflow as tf

# 상수 선언
scalar = tf.constant(1)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(tf.rank(scalar))
print(tf.rank(vector))
print(tf.rank(matrix))
print(tf.rank(tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [4]:
a = tf.zeros(1)
b = tf.zeros([2])
c = tf.zeros([2, 3])

print(a)
print(b)
print(c)

tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([0. 0.], shape=(2,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


텐서 (Tensor)는 NumPy 어레이와 비슷하지만,

텐서는 GPU, TPU와 같은 가속기에서 사용할 수 있고,

텐서는 값을 변경할 수 없습니다.

In [3]:
### 텐서를 NumPy 어레이로
### 텐서의 numpy() 메서드를 사용해서 텐서를 NumPy 어레이로 변환할 수 있습니다.
import tensorflow as tf

a = tf.constant([1, 2, 3])

print(a)
print(a.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]


In [ ]:
### NumPy 어레이를 텐서로
### 반대로, 다양한 TensorFlow 연산은 자동으로 NumPy 어레이를 텐서로 변환합니다.
import numpy as np

b = np.ones(3)

print(b)
print(tf.multiply(b, 3))