# 기하학적 변환 (Geometric transformation)

## 이동변환 (translate)

In [ ]:
# warpAffine(src, M, dsize[, dst[, flags[, borderMode[, borderValue]]]]) -> dst
# src: 입력영상
# M: affine transform matrix (size: 2 x 3)
# dsize: 출력영상 크기, (0, 0) = 입력영상크기로 출력
# borderValue: 값이 없는 영역을 채우는 값, default  = 0

In [1]:
import sys
import numpy as np
import cv2


src = cv2.imread('fig/puppy.bmp')

if src is None:
    print('Image load failed!')
    sys.exit()

affine = np.array([[1, 0, 200],
                [0, 1, -100]], dtype=np.float32)

dst = cv2.warpAffine(src, affine, (0, 0))

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

## 영상확대 (Scaling)

In [ ]:
# resize(src, dsize[, dst[, fx[, fy[, interpolation]]]]) -> dst
# src: 입력영상
# dsize: 출력영상의 크기
# fx, fy: 0, 0
# interpolation

In [23]:
import sys
import numpy as np
import cv2


src = cv2.imread('fig/rose.jpg') # src.shape=(320, 480)
print(src.shape)
if src is None:
    print('Image load failed!')
    sys.exit()

dst1 = cv2.resize(src, (1920, 1280), interpolation=cv2.INTER_NEAREST)
dst2 = cv2.resize(src, (1920, 1280))  # cv2.INTER_LINEAR (Bilinear)
dst3 = cv2.resize(src, (1920, 1280), interpolation=cv2.INTER_CUBIC)
dst4 = cv2.resize(src, (1920, 1280), interpolation=cv2.INTER_LANCZOS4)

cv2.imshow('src', src)
cv2.imshow('INTER_NEAREST', dst1[800:1600, 800:1200])
cv2.imshow('Bilinear', dst2[800:1600, 800:1200])
cv2.imshow('INTER_CUBIC', dst3[800:1600, 800:1200])
cv2.imshow('INTER_LANCZOS4', dst4[800:1600, 800:1200])
cv2.waitKey()
cv2.destroyAllWindows()


(461, 600, 3)


## 회전변환 (Rotation)

In [ ]:
# warpAffine(src, M, dsize[, dst[, flags[, borderMode[, borderValue]]]]) -> dst
# src: 입력영상
# M: affine transform matrix (size: 2 x 3)
# dsize: 출력영상 크기, (0, 0) = 입력영상크기로 출력
# borderValue: 값이 없는 영역을 채우는 값, default  = 0

# getRotationMatrix2D(center, angle, scale) -> retval
# center: 영상의 center
# angle: 회전각도
# scale: 확대율

In [35]:
import sys
# import math
import numpy as np
import cv2


src = cv2.imread('fig/puppy.bmp')

if src is None:
    print('Image load failed!')
    sys.exit()

# rad = 20 * np.pi / 180
# affine = np.array([[np.cos(rad), np.sin(rad), 0],
#                 [-np.sin(rad), np.cos(rad), 0]], dtype=np.float32)

cp = (src.shape[1] / 2, src.shape[0] / 2)

affine = cv2.getRotationMatrix2D(cp, 20, 1)

dst = cv2.warpAffine(src, affine, (0, 0))

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()

cv2.destroyAllWindows()


<ufunc 'cos'>

## Shearing

In [10]:
import sys
import numpy as np
import cv2


src = cv2.imread('fig/puppy.bmp')

if src is None:
    print('Image load failed!')
    sys.exit()

aff = np.array([[1, 0, 0],
                [0.2, 1, 0]], dtype=np.float32)

h, w = src.shape[:2]
dst = cv2.warpAffine(src, aff, (w + int(h * 0.2), h))

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()


## Warp perspective

In [ ]:
# getPerspectiveTransform(src, dst[, solveMethod]) -> retval
# src: 입력영상의 4개 좌표점, numpy array shape(4,2)
# dst: 출력영상의 4개 좌표점, numpy array shape(4,2)

In [15]:
import sys
import numpy as np
import cv2


src = cv2.imread('fig/checkerboard.png')

if src is None:
    print('Image load failed!')
    sys.exit()


h, w = src.shape[:2]

srcQuad = np.array([[217, 50], [691, 47], [830, 517], [67, 526]], np.float32)
dstQuad = np.array([[0, 0], [w-1, 0], [w-1, h-1], [0, h-1]], np.float32)

pers = cv2.getPerspectiveTransform(srcQuad, dstQuad)
dst = cv2.warpPerspective(src, pers, (w, h))

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

781 63


##  Remapping

In [ ]:
# remap(src, map1, map2, interpolation[, dst[, borderMode[, borderValue]]]) -> dst

In [19]:
import sys
import numpy as np
import cv2


src = cv2.imread('fig/bamboo.jpg')
#
if src is None:
    print('Image load failed!')
    sys.exit()

h, w = src.shape[:2]

map2, map1 = np.indices((h, w), dtype=np.float32)
print(map2)
print(map2.shape)
map1 = map1 + 10 * np.sin(map2/32)

print(np.sin(map2/32))
dst = cv2.remap(src, map1, map2, cv2.INTER_CUBIC, borderMode=cv2.BORDER_DEFAULT)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()

cv2.destroyAllWindows()

[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   1.   1. ...   1.   1.   1.]
 [  2.   2.   2. ...   2.   2.   2.]
 ...
 [597. 597. 597. ... 597. 597. 597.]
 [598. 598. 598. ... 598. 598. 598.]
 [599. 599. 599. ... 599. 599. 599.]]
(600, 498)
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.03124491  0.03124491  0.03124491 ...  0.03124491  0.03124491
   0.03124491]
 [ 0.06245932  0.06245932  0.06245932 ...  0.06245932  0.06245932
   0.06245932]
 ...
 [-0.19210428 -0.19210428 -0.19210428 ... -0.19210428 -0.19210428
  -0.19210428]
 [-0.16134752 -0.16134752 -0.16134752 ... -0.16134752 -0.16134752
  -0.16134752]
 [-0.13043322 -0.13043322 -0.13043322 ... -0.13043322 -0.13043322
  -0.13043322]]
