In [1]:
import numpy as np

x = np.arange(8)
print(x)

[0 1 2 3 4 5 6 7]


In [3]:
# 곱하면 값이 손실된다.(8개 -> 5개)
tx = x*1.5
print(tx)

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5]


In [4]:
# 나누면 값이 손실되지 않는다.(16개 -> 16개)
x1 = np.arange(16)
print(x1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
tx1 = x1/1.5
print(tx1)

[ 0.          0.66666667  1.33333333  2.          2.66666667  3.33333333
  4.          4.66666667  5.33333333  6.          6.66666667  7.33333333
  8.          8.66666667  9.33333333 10.        ]


In [ ]:
# 따라서 큰 화면을 준비하고, 축소하는게 더 좋다. 