In [2]:
import numpy as np

In [6]:
# 1 차원 배열 생성
x1 = np.array([1.0, 2.0, 3.0])
x2 = np.array([5.0, 10.0, 15.0])
print(x1, x2)
print(type(x1), type(x2))

# list로 보이지만 실제로는 array 타입

[1. 2. 3.] [ 5. 10. 15.]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [7]:
# 2차원 배열 생성
y1 = np.array([[1.0, 2.0], [3.0, 4.0]])
y2 = np.array([[5.0, 10.0], [15.0, 20.0]])

print(y1, y2)
print(type(y1), type(y2))

[[1. 2.]
 [3. 4.]] [[ 5. 10.]
 [15. 20.]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [8]:
# numpy 원소에 접근 x1[0] -> 1.0
print(x1[0])
print(y1[0][0])

1.0
1.0


In [11]:
# list를 numpy array type으로 변경
a_list = [1.0, 2.0, 3.0]
a_np = np.array(a_list)
print(a_np, type(a_np))

[1. 2. 3.] <class 'numpy.ndarray'>


In [17]:
# numpy array 생성
arr = np.arange(15)
print(arr.ndim, arr.shape, arr.size)

# 2차원 reshape를 한 경우 확인
arr = np.arange(20).reshape(4, 5)
print(arr.ndim, arr.shape, arr.size)

# 3차원으로 reshape를 한 경우 확인
arr = np.arange(20).reshape(2, 2, 5)
print(arr.ndim, arr.shape, arr.size,
      arr.dtype.name, arr.dtype.itemsize)

# float형 사용
arr = np.arange(-5, 5, 0.5).reshape(4,5)
print(arr.ndim, arr.shape, arr.size,
      arr.dtype.name, arr.dtype.itemsize)

1 (15,) 15
2 (4, 5) 20
3 (2, 2, 5) 20 int32 4
2 (4, 5) 20 float64 8


In [36]:
# numpy 특이한 값
# infinity 무한대를 표현 : inf로 표시
# not a number 정의할 수 없는 숫자 : nan으로 표시

# 배열 생성 : array
arr = np.empty((4,3)) # 4 by 3 배열 생성, -> 알 수 없는 값이 들어옴
print(arr)

# 초기값을 부여하면서 array 생성
arr = np.zeros(5)
print(arr)

arr = np.zeros((2,3))
print(arr)

# 1로 초기화 
arr = np.ones((3, 4))
print(arr, arr.dtype, arr.dtype.name, arr.dtype.itemsize)

# 1로 초기화하는데 int 형식으로 초기화
arr = np.ones((3, 4), dtype='i')
print(arr, arr.dtype, arr.dtype.name, arr.dtype.itemsize)

arr = np.ones((3, 4), dtype='i8')
print(arr, arr.dtype, arr.dtype.name, arr.dtype.itemsize)

# 1로 초기화하는데 문자 형식으로 초기화
arr = np.ones((3, 4), dtype='U4') # U4 : 문자(4byte)
print(arr, arr.dtype, arr.dtype.name, arr.dtype.itemsize)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 float64 8
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int32 int32 4
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int64 int64 8
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']] <U4 str128 16


In [37]:
# 문자로 초기화하고
a = np.zeros(5, dtype='U4')
print(a, arr.dtype, arr.dtype.name, arr.dtype.itemsize)

# 그것을 1로 다시 재초기화 한다.
arr = np.ones_like(a, dtype='f')
print(arr, arr.dtype, arr.dtype.name, arr.dtype.itemsize)

['' '' '' '' ''] <U4 str128 16
[1. 1. 1. 1. 1.] float32 float32 4


In [49]:
# array 연산
x1 = np.array([1.0, 2.0, 3.0])
y1 = np.array([5.0, 10.0, 15.0])

x2 = np.array([[1.0, 2.0], [3.0, 4.0]])
y2 = np.array([[5.0, 10.0], [15.0, 20.0]])

z1 = np.array([-1.0, -2.0])
z2 = np.array([[5.0], [10.0], [15.0]])

print(x1 + y1); print()
print(x1 - y1); print()
print(x1 * y1); print()
print(x1 / y1); print()

print(x2 + y2); print()
print(x2 - y2); print()
print(x2 * y2); print()
print(x2 / y2); print()



[ 6. 12. 18.]

[ -4.  -8. -12.]

[ 5. 20. 45.]

[0.2 0.2 0.2]

[[ 6. 12.]
 [18. 24.]]

[[ -4.  -8.]
 [-12. -16.]]

[[ 5. 20.]
 [45. 80.]]

[[0.2 0.2]
 [0.2 0.2]]

[[0. 0.]
 [2. 2.]]

[[2. 4.]
 [4. 6.]]

[[-1. -4.]
 [-3. -8.]]

[[-1. -1.]
 [-3. -2.]]

[1. 2. 3. 4.]
[[1. 2.]
 [3. 4.]]


In [52]:
x1 = np.array([1.0, 2.0, 3.0])
x2 = np.array([[1.0, 2.0], [3.0, 4.0]])
z1 = np.array([-1.0, -2.0])

# 사로 행열이 맞지 않으면, broad cast가 실행된다.
# z1은 2차원 배열이 없으나, x2 - z1이 가능하다.
print(x2 + z1); print()
print(x2 - z1); print()
print(x2 * z1); print()
print(x2 / z1); print()
print(x1 ** 2); print()
print(x1 >=2); print()

# 배열의 형변환
# x2는 2차원 배열이나 -> 1차원으로 줄임ㅈ
print(x2.flatten()) # 평탄화 시킴 : 모든 차수의 배열을 1차원으로
print(x2.reshape(2,2))

# 코드 한 줄에 평탄화 후에 resape까지 완료
print(x2.flatten().reshape(2,2))

[[0. 0.]
 [2. 2.]]

[[2. 4.]
 [4. 6.]]

[[-1. -4.]
 [-3. -8.]]

[[-1. -1.]
 [-3. -2.]]

[1. 4. 9.]

[False  True  True]

[1. 2. 3. 4.]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [61]:
# array indexing
# indexcing, slicing and iterating

a = np.arange(10)**2 # 0  1  4  9 16 25 36 49 64 81 즉 n^2로 초기화(n=1,2,3...)
print(a)

print(a[3:5], print(a[2])) # 3, 4번째 값

# reverse 나열
print(a[::-1]) # start : end : -1 (step) 뒤에서 출력 
a[0:6:2] = -a[0:6:2] # start : end : step
print(a)

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16] None
[81 64 49 36 25 16  9  4  1  0]
[  0   1  -4   9 -16  25  36  49  64  81]


In [62]:
# 반복문
for x in a:
    print(x+1, end=' ')
    
a = np.arange(1, 21, 1).reshape(4, 5)
print(a)
print(a[1,1]) # 7
print(a[:2,]) # [행, 열] # rows 0, 1이 출력

1 2 -3 10 -15 26 37 50 65 82 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
7
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [71]:
# numpy 일반 함수
a = np.arange(0, 6, 1) # array[0,1,2,3,4,5]
print(a)
print(np.sin(a), np.cos(a))

a = np.arange(0.01, 1, 0.05)
print(np.log(a))

a1 = np.array([10,3,4])
a2 = np.array([4,5,6])

# 값 비교
print(np.maximum(a1, a2))
print(np.minimum(a1, a2))

[0 1 2 3 4 5]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]
[10  5  6]
[4 3 4]


In [80]:
# array의 합
print(np.sum(a1))
print(np.sum(a2))

# 랜덤 선택
print(np.random.choice(100, 5)) # 0에서 100사이의 수 중에서 5개의 숫자를 램덤 선택
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])) # 0에서 10사이의 수 중에서 5개의 숫자를 p확률에 따라서 선택
print(np.random.rand(2,3))
print(np.random.randn(2,3))

17
15
[61 80 53 75 92]
[2 3 3 2 3 3 3 0 3 3]
[[0.05371506 0.56549797 0.25444535]
 [0.31514916 0.83339475 0.13943893]]
[[-0.74902056 -1.12389942 -1.03101393]
 [-0.48556318 -0.21998652 -0.35533328]]


In [79]:
# 
a = np.array([6,1,3,2,4,5])
print(a[np.argmax(a)]) # np.argmax(array) : 가장 큰 값의 인덱스 반환 : 값이 제일 큰 것은 6이고, index는 1
print(a[np.argmin(a)]) # np.argmin(array) : 가장 작은 값의 인덱스 반환

a = np.array([[0.1, 0.8, 0.2], 
              [0.3, 0.2, 0.5], 
              [0.9, 0.5, 0.3]])

# index를 각각 2, 0, 1을 반환했음. 
# 0.9가 rows 2이기 때문에 인덱스 2 반환, 즉(columns 0인 값에서 가장 큰 값은 [2, 0]에 있다.) 
# 0.8이 0.2, 0.5보다 크기 때문에 인덱스 0 반환
# 0.5가 0.2, 0.3보다 크기 때문에 인덱스 1 반환
print("===", np.argmax(a, axis=0)) 

6
1
=== [2 0 1]


In [93]:
# 다음 행렬과 같은 배열이 있다.
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

# 이 배열에서 3의 배수를 찾아라
for num in x:
    if num % 3 == 0:
        print(num)
        
        
print()
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
for num in x:
    if num % 4 == 1:
        print(num)

print()
# 이베열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
for num in x:
    if (num % 3 == 0) & (num % 4 == 1):
        print(num)

3
6
9
12
15
18

1
5
9
13
17

9


In [91]:
# 방법 2
arr = np.arange(1,21,1)
print(arr[arr%3==0])
print(arr[arr%4==1])
print(arr[(arr%3==0) & (arr%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
